#!/bin/bash
# Gera peças do ninja em camadas pelo Codex: cada peça num pedido separado, desenhada por cima do MOLDE dela (o corpo
# já montado com as peças de baixo: python scripts/prepare-layers.py tpl <peça>) numa cor-chave, em folha inteira +
# vista de lado 2×2. Depois: python scripts/prepare-layers.py <peça>
# Cores-chave: magenta = cor principal (recolorida), amarelo = segunda cor, ciano = metal, verde = cabelo.
# Uso: bash scripts/layer-pieces.sh <peça> [peça ...]
cd "$(dirname "$0")/.."
D=docs/arte/layers
FULL="Image 1 is a pixel art sprite sheet: 4 columns x 3 rows, the same chibi ninja in 12 walking poses (row 1 side view facing right, row 2 front view, row 3 back view). Redraw Image 1 EXACTLY: same 12 characters, same positions in the image, same sizes, same poses, same body, face, hair and clothes with the same colors, same pixel art style, white background. Change NOTHING except adding the item below on every one of the 12 characters, fitted to each pose and view (side, front, back)."
SIDE="Image 1 shows 4 pixel art sprites (2 x 2 grid) of the same chibi ninja in SIDE VIEW facing RIGHT, walking. Redraw Image 1 EXACTLY: same 4 characters, same positions, same sizes, same poses, same body, face, hair and clothes with the same colors, same pixel art style, white background. Change NOTHING except adding the item below on all 4 characters, seen from the side."
MAG="pure magenta key color (#ff00ff, darker shading #a0009f, highlight #ff8cff)"
YEL="pure yellow key color (#ffee00, darker shading #b0a000, highlight #fff799)"
CYA="pure cyan key color (#00e5ff, darker shading #0090a0, highlight #9ff6ff)"
END="Dark pixel outline. The key colors are used ONLY on this item, nowhere else."
declare -A ITEM
ITEM[headband]="ADD: a ninja forehead protector headband tied around the forehead, sitting ON the hair (the hair spikes stay visible above and behind it), with the knot and two cloth tails hanging at the back of the head. The cloth band and tails are ONLY $MAG; the metal plate on the forehead is ONLY $CYA. In the back view only the band, knot and tails show. $END"
ITEM[vest-jounin]="ADD: a jounin tactical flak vest worn over the torso, with a thick rolled high collar, two rows of scroll pouches on the chest and metal shoulder guards. The vest is ONLY $MAG; the shoulder guards and buckles are ONLY $CYA. The sleeves and pants underneath stay visible. It is a vest worn on the body, NOT a backpack. $END"
ITEM[coat-sannin]="ADD: a legendary sannin long overcoat: an open sleeveless haori coat over the clothes, reaching below the knees, with a broad trim along its front edges and hem and a big round emblem on the back. The coat is ONLY $MAG; the trim and the emblem are ONLY $YEL. The clothes underneath show at the front opening and the arms. $END"
ITEM[cloak-kage]="ADD: a Kage ceremonial cloak: a long flowing haori cloak over the shoulders reaching the ankles, with wide sleeves, open at the front. The cloak is ONLY $MAG; a flame pattern along the bottom hem and a big fire kanji on the back are ONLY $YEL. The clothes underneath show at the front opening. $END"
ITEM[hat-kage]="ADD: a Kage hat: a wide shallow conical kasa hat on the bald head, wider than the shoulders, with a diamond panel on the front showing a fire kanji, and a long cloth veil hanging from the back of the hat down to the shoulders. The hat and the veil are ONLY $MAG; the front diamond panel with the kanji and the trim of the brim are ONLY $YEL. The face stays visible under the brim. $END"
ITEM[sword-zabuza]="ADD: a giant executioner cleaver sword carried diagonally on the back (like Zabuza's Kubikiribocho): a huge flat rectangular blade almost as tall as the character, with a round hole near the tip and a half-moon notch on the back edge, and a long wrapped handle sticking up over the right shoulder. The blade is ONLY $CYA; the handle wrapping is ONLY $MAG. Front view: only the handle over the shoulder and the blade edges behind the body; back view: the whole blade across the back; side view: the blade diagonally behind the back. $END"
GRN="pure green key color (#2ecc40, darker shading #1e8a2b, highlight #7dff8a)"
HAIR="The hair is ONLY $GRN with a dark pixel outline and covers the whole top of the skull (no bald skin visible on top); the face, eyes and ears stay visible. No headband. No other green anywhere."
ITEM[hair-ponytail]="ADD: anime hair tied in a long high ponytail: smooth hair on top with short side bangs framing the face, gathered at the back of the head and falling as one thick ponytail down to the middle of the back (side view: the ponytail hangs behind the head; back view: it hangs down the middle of the back; front view: only the bangs and the tip of the ponytail behind one side). $HAIR"
ITEM[hair-short]="ADD: short neat anime hair, cropped close to the head with a few soft tufts on top and short bangs on the forehead, ending above the ears and the neck (much smaller than spiky hair). $HAIR"
ITEM[hair-long]="ADD: long straight loose anime hair with straight bangs on the forehead, falling behind the shoulders down to the middle of the back (front view: two locks fall in front of the shoulders beside the face, the face stays clear; side view: the hair falls behind the head and down the back; back view: a wide curtain of hair down the back). $HAIR"
ITEM[hair-buns]="ADD: anime hair with two round buns on top of the head, one on each side (like Tenten), with short bangs on the forehead; the rest of the hair is pulled up smoothly into the buns (side view: one bun visible on top and the other peeking behind; back view: both buns). $HAIR"

ON_BACK="Side view: seen from the side behind the back; back view: the whole weapon on the back; front view: only the parts that stick out over the shoulders or beside the body."
ITEM[sword-samehada]="ADD: the Samehada great sword carried vertically on the back (like Kisame's): a huge thick club-like blade almost as tall as the character, covered in rows of small spiky scales, partly wrapped in bandages, with the handle sticking up over the right shoulder. The scaled blade is ONLY $MAG; the bandage wrappings are ONLY $YEL; the metal pommel is ONLY $CYA. $ON_BACK $END"
ITEM[sword-kiba]="ADD: the Kiba twin lightning swords: two short swords with jagged lightning-bolt shaped blades, crossed in an X on the back, one handle over each shoulder. The blades are ONLY $CYA; the handles are ONLY $MAG; small crackling sparks along the blade edges are ONLY $YEL. $ON_BACK $END"
ITEM[sword-hiramekarei]="ADD: the Hiramekarei sword carried diagonally on the back: a broad flat blade completely wrapped in cloth bandages, with TWO handles side by side at the top sticking up over the right shoulder. The bandage wrapping is ONLY $MAG; the two handles are ONLY $YEL; the metal tip at the bottom is ONLY $CYA. $ON_BACK $END"
ITEM[sword-nuibari]="ADD: the Nuibari needle sword carried diagonally on the back: a very long thin sword shaped like a giant sewing needle, with a long wire thread coiled from the eye at the end of the handle. The needle blade is ONLY $CYA; the handle wrap is ONLY $MAG; the coiled wire thread is ONLY $YEL. $ON_BACK $END"
ITEM[sword-kabutowari]="ADD: the Kabutowari weapon: a big one-sided battle axe carried on the back with its handle over the right shoulder, linked by a chain to a small round hammer hanging at the left hip. The axe blade and the hammer head are ONLY $CYA; the axe handle and the hammer handle are ONLY $MAG; the chain is ONLY $YEL. $END"
ITEM[sword-shibuki]="ADD: the Shibuki explosive sword carried diagonally on the back: a broad sword whose blade is made of a big rolled scroll of explosive paper tags held in a metal frame, with the handle over the right shoulder. The metal frame is ONLY $CYA; the scroll of paper tags is ONLY $YEL; the handle is ONLY $MAG. $ON_BACK $END"
ITEM[sword-kusanagi]="ADD: the Kusanagi straight sword (a chokuto, like Sasuke's) in its sheath tucked diagonally at the back of the waist into a thick purple rope belt tied around the waist, the handle sticking out at the left hip. The sheath and the handle are ONLY $MAG; the thick rope belt with its big bow knot is ONLY $YEL; the guard and the pommel are ONLY $CYA. Side view: the sheath behind the hip; front view: the rope belt and the handle at the hip; back view: the sheath across the lower back. $END"
ITEM[sword-sakumo]="ADD: the White Light chakra sabre (Kakashi's father's tanto): a short sword in its sheath strapped HORIZONTALLY across the lower back, the handle sticking out at the right hip. The sheath is ONLY $MAG; the handle wrapping is ONLY $YEL; the guard and metal fittings are ONLY $CYA. Side view: the handle at the hip and the sheath behind; front view: only the handle at the hip; back view: the whole sheath across the lower back. $END"
ITEM[sword-asuma]="ADD: a pair of trench knives (like Asuma's chakra blades): two short triple-edged metal blades with knuckle-guard grips, holstered on a belt at both hips, blades pointing down. The blades are ONLY $CYA; the grips and holsters are ONLY $MAG; the belt is ONLY $YEL. Front and back view: one knife on each hip; side view: the knife on the visible hip. $END"
ITEM[sword-raijin]="ADD: the Thunder God sword (Tobirama's Raijin no Ken): a sword in its sheath at the left hip, with small crackling lightning bolts sparking around the handle and the sheath. The sheath and the handle are ONLY $MAG; the crackling lightning is ONLY $YEL; the guard is ONLY $CYA. Side view: the sheath at the hip pointing back; front view: the handle at the hip; back view: the end of the sheath behind the hip. $END"
ITEM[sword-bee]="ADD: seven katana swords carried on the back (like Killer Bee's seven swords style), spread out in a fan with the handles sticking up over both shoulders like a peacock tail. The sheaths are ONLY $MAG; the handles are ONLY $YEL; the round guards are ONLY $CYA. $ON_BACK $END"
ITEM[sword-tanto]="ADD: an ANBU tanto: a short straight sword in its sheath strapped diagonally on the back, the handle sticking up over the right shoulder. The sheath is ONLY $MAG; the handle wrapping is ONLY $YEL; the guard is ONLY $CYA. $ON_BACK $END"
ITEM[outfit-anbu]="ADD: an ANBU black-ops uniform over the dark gray bodysuit (the bodysuit stays dark gray, arms bare from the shoulder): a light segmented chest armor plate (breastplate) over the torso with shoulder straps, metal arm guards on both forearms, and long gloves up to the elbows. The breastplate and its shoulder straps are ONLY $MAG; the long gloves are ONLY $YEL; the forearm guards are ONLY $CYA. No headband, no mask, no hair. $END"
MASK="covering the WHOLE FACE (front view: the mask covers the face from the forehead to the chin, two narrow eye holes; side view: the mask in profile over the face with its snout or beak sticking forward; back view: only the thin strap across the back of the head under the hair). The hair stays visible above and behind the mask. The mask is ONLY $MAG; the painted markings on it are ONLY $YEL. $END"
declare -A ANIMAL=([fox]="a FOX mask: pointed fox ears on top, a narrow pointed snout, sharp painted markings around the eyes and on the cheeks" [tiger]="a TIGER mask: small round ears, a wide muzzle, painted tiger stripes on the forehead and cheeks" [crow]="a CROW mask: a long pointed black-bird beak sticking forward, painted feather markings around the eyes" [owl]="an OWL mask: two small feather tufts on top like horns, big round painted rings around the eyes, a tiny hooked beak" [boar]="a BOAR mask: a flat round pig snout with two nostrils, two small curved tusks, short pointed ears, painted markings on the brow" [hawk]="a HAWK mask: a short hooked raptor beak, sharp painted swept-back markings from the eyes like wings" [bear]="a BEAR mask: two round ears on top, a short wide muzzle, a painted crescent mark on the forehead" [monkey]="a MONKEY mask: a round face with big round ears on the sides, a short flat nose, painted markings around the eyes and mouth")
for a in "${!ANIMAL[@]}"; do ITEM[mask-$a]="ADD: an ANBU porcelain animal mask, ${ANIMAL[$a]}, $MASK"; done
gen() {
  local p=$1 view=$2
  # máscara é pequena e rígida: só a folha inteira (sem a vista de lado ampliada)
  [ "$view" = side ] && [[ $p == mask-* ]] && return
  if [ "$view" = side ]; then
    node scripts/codex-image.mjs "$D/$p-side.png" "$SIDE ${ITEM[$p]}" --ref "$D/tpl-$p-side.png" --size 1536x1024
  else
    node scripts/codex-image.mjs "$D/$p.png" "$FULL ${ITEM[$p]}" --ref "$D/tpl-$p.png" --size 1536x1024
  fi
}
[ $# -eq 0 ] && { echo "uso: bash scripts/layer-pieces.sh <peça> [peça ...]   (peças: ${!ITEM[*]})"; exit 1; }
# 2 peças por vez (4 gerações em paralelo)
while [ $# -gt 0 ]; do
  gen "$1" full & gen "$1" side &
  [ -n "$2" ] && { gen "$2" full & gen "$2" side & }
  wait
  shift; [ $# -gt 0 ] && shift
done
