#!/usr/bin/env bash
# Pede ao Codex mockups (imagens) das telas do jogo, todas no estilo do quadro de missões aprovado.
# uso: bash scripts/mockups.sh [nome...]   (sem nomes = todas). Saída em docs/arte/mockups/<nome>.png
cd "$(dirname "$0")/.." || exit 1
OUT=docs/arte/mockups
STYLE=$OUT/missoes-mockup.png
mkdir -p "$OUT"

COMMON="You are a senior game UI designer. Use your image generation tool to create ONE image, 1536x1024, a UI MOCKUP (redesign) of a screen of the game 'Vila Ninja' (pixel-art ninja village builder inspired by Naruto, isometric map, mobile-first landscape but also desktop). The attached image is the APPROVED redesign of another screen (Quadro de missões): copy EXACTLY its visual language: dark brown translucent window, warm orange accent buttons, cream text, rounded cards with subtle borders, small line icons (no emoji), colored pills for status, chips for numbers, pixel-art portraits/illustrations where they help, the game map faintly visible behind. All text in Brazilian Portuguese, crisp and legible, realistic data. Before drawing, READ the source code mentioned below (read only, do not change any project file) to know exactly what information and actions this screen has today, then reorganize it with clear hierarchy, less clutter and a more game-like feel. Save the image as"

declare -A P
P[ninjas]="ninjas.png in the folder $OUT. Do not create or change any other file. SCREEN: window 'Ninjas' (tabs Ninjas | Equipes | Clãs), tab Ninjas selected: the roster of the village ninjas. Read src/ui/panel.ts methods roster(), gearBar(), rookieBar(), teachBar() and the RosterFilter/ROSTER_SORTS definitions. Show filters (Todos, Sem equipe, Em equipe, Em missão, Feridos, Genin, Chunin, Jounin, Sannin, Kage) and sort, the bulk actions (Equipar todos, Automático, Proteger novatos, Ensinar todos) compacted into a toolbar, and a grid of ninja cards with pixel portrait, name, rank badge, level, HP/chakra bars, team color, jutsus, status (treinando, em missão, ferido)."
P[equipes]="equipes.png in the folder $OUT. Do not create or change any other file. SCREEN: window 'Ninjas', tab Equipes selected: list of teams and the team detail. Read src/ui/panel.ts methods teamsList() and teamView(), and src/game/teams.ts. Show team cards (color, name, sensei, members portraits, power, current mission/free) and on the right the selected team detail with members, formation/orders, sensei slot, and actions."
P[ficha]="ficha.png in the folder $OUT. Do not create or change any other file. SCREEN: the right-side DRAWER (narrow panel, about 1/3 of the screen width, full height, game map visible on the left) that opens when the player taps a ninja on the map. Read src/ui/panel.ts methods unit(), equipSection(), teamSection() and the unit tabs (Ficha, Ordens, Equipar). Show the 'Ficha' tab: big pixel portrait, name, rank, level, HP/chakra/XP bars, attributes, jutsus, basic techniques (Shunshin, Kawarimi), profession, ninken, team; keep it compact and scannable."
P[predio]="predio.png in the folder $OUT. Do not create or change any other file. SCREEN: the right-side DRAWER (narrow panel, about 1/3 of screen width, game map visible on the left) that opens when the player taps a BUILDING. Example building: Campo de Treino nível 2. Read src/ui/panel.ts methods building(), upgradeSection(), fieldSection(), interiorSection() and src/ui/maptip.ts. Show header with building pixel art, name, level stars, the upgrade card with cost, the interior preview (who is inside), workers +/- control, field focus chips and slots, and the move/demolish actions at the bottom."
P[vila]="vila.png in the folder $OUT. Do not create or change any other file. SCREEN: window 'Vila' (tabs Vila | Kage | Estatísticas), tab Vila selected. Read src/ui/panel.ts methods villageSection(), lifeSection(), villageView() and src/game/village.ts, src/game/mood.ts. Show village level progression (next level requirements checklist and upgrade button), population/happiness with its factors, season/weather, festival action."
P[kage]="kage.png in the folder $OUT. Do not create or change any other file. SCREEN: window 'Vila', tab Kage selected. Read src/ui/panel.ts methods kageSection(), sanninSection(), orgSection() and src/game/kage.ts, src/data/kageArts.ts, src/data/sannin.ts, src/data/org.ts. Show the current Kage (portrait, kage art Hiraishin), the Three Sannin slots (toad/snake/slug paths, empty or filled, candidates), and the 'Ordem do Eclipse' threat tracker (8 members, defeated ones crossed, next appearance)."
P[mundo]="mundo.png in the folder $OUT. Do not create or change any other file. SCREEN: window 'Mundo' (tabs Região | Expedições), tab Região selected. Read src/ui/panel.ts methods regionView(), regionNodeSection(), expeditionsView() and src/data/region.ts. The region is a painted map (src/art/region.jpg, look at it) with places (villages, islands, sacred places, the hideout) as markers; show the map big, a selected place card with relation/status and actions (Comerciar, Proteger, Saquear, Anexar, Explorar...) with team picker, and active expeditions as compact cards."
P[oficinas]="oficinas.png in the folder $OUT. Do not create or change any other file. SCREEN: window 'Oficinas' (Forja, Farmácia, Oficina de Selos side by side). Read src/ui/panel.ts method craftsView() and src/game/gear.ts, src/game/automation.ts, src/data/items.ts. Show each workshop as a column with its pixel art, level, stock of items, production queue with progress, recipes with cost and the auto-craft 'Manter N' controls, plus Equipar todos / Automático toolbar."
P[hud]="hud.png in the folder $OUT. Do not create or change any other file. SCREEN: the main game HUD over the isometric pixel-art village map, landscape. Read src/ui/hud.ts, src/ui/index.ts (dock buttons), src/ui/build.ts (build bar) and src/ui/styles.css. Show the top bar (resources with icons, population, happiness, day/time/season/weather, speed controls, fullscreen and menu), the bottom dock buttons (Construir, Ninjas, Vila, Missões, Mundo, Oficinas, Selecionar) and the build list open as a strip of building cards ABOVE the dock, plus one alert banner. Make it cleaner and more polished but keep the map dominant."

NAMES=("$@")
[ ${#NAMES[@]} -eq 0 ] && NAMES=(ninjas equipes ficha predio vila kage mundo oficinas hud)
for n in "${NAMES[@]}"; do
  (
    t0=$(date +%s)
    printf '%s %s' "$COMMON" "${P[$n]}" | codex exec --skip-git-repo-check -m gpt-5.5 -s workspace-write -C . -i "$STYLE" - > "$OUT/$n.codex.txt" 2>&1
    if [ -f "$OUT/$n.png" ]; then echo "ok $n ($(( $(date +%s) - t0 ))s)"; else echo "FALHOU $n (veja $OUT/$n.codex.txt)"; fi
  ) &
done
wait
